site_name: "Template for ML API"
nav:
  - Accueil: index.md
  - Documentation:
      - API:
          - Introduction: api/introduction.md
      - Scraping:
          - Introduction: scraping/introduction.md
          - Models: scraping/models.md
theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            rendering:
              show_source: true